/**
 * Shell terminals — a real login shell per thread, for the app's terminal dock.
 *
 * Distinct from ./pty-turn.mjs, which hosts an AGENT CLI so the app can answer
 * its prompts. This is the plain shell a person types into: same PTY machinery
 * underneath (./pty.mjs), different lifetime and a different consumer.
 *
 * Kept in its own registry keyed `thread id → shell`, deliberately NOT the agent
 * PtyManager: that one is keyed by thread id too, and sharing it would mean
 * opening the dock on a thread killed the agent PTY backing it (PtyManager
 * .create SIGKILLs an existing session under the same key). Two registries, no
 * collision.
 *
 * ── What goes over the wire ───────────────────────────────────────────────
 *
 * Two formats, and both matter:
 *
 *   cells  the RENDERED screen as coloured runs (./screen.mjs). The macOS app
 *          has no terminal emulator of its own, so the bridge emulates and
 *          ships a picture. Only rows that changed, coalesced at a frame
 *          interval — a shell printing one line costs one row.
 *
 *   raw    the PTY's bytes, untouched. Nothing consumes this yet; it exists so
 *          a client with its own emulator (expo-libghostty on the phone, which
 *          is explicitly bring-your-own-PTY) can attach to these same endpoints
 *          without the bridge changing. Cheap to serve, and it keeps the
 *          transport from being welded to one renderer.
 *
 * The emulator is fed either way, because it's also what answers the shell's
 * own queries — see the DA/DSR note in `attach`.
 */
import os from "node:os";
import { existsSync } from "node:fs";
import { PtySession } from "./pty.mjs";
import { agentEnv } from "./env.mjs";

/** Default grid. The client resizes to its real size as soon as it lays out;
 *  this is only what the shell sees for the first few milliseconds. */
const COLS = 100;
const ROWS = 24;

/**
 * Frame interval for `cells` streaming, in ms.
 *
 * A shell can emit thousands of writes a second (`yes`, a build log) and the
 * eye reads none of them. Coalescing to ~20fps means the cost of a firehose is
 * bounded by the frame rate rather than by the program's output rate — without
 * it, `cat` of a large file would render every intermediate scroll state.
 */
const FRAME_MS = 50;

/** Idle shells are killed after this long with nobody attached, so a dock
 *  opened once on a thread you never return to doesn't hold a shell forever. */
const REAP_MS = 30 * 60_000;

/**
 * The user's login shell, and the argv that makes it interactive.
 *
 * `-l` is deliberate: without a login shell the PATH is whatever the bridge was
 * launched with, which for a GUI-launched app is the bare system PATH — no
 * Homebrew, no nvm, no pyenv. A terminal that can't find the tools the user
 * installed is not a terminal they can use.
 */
function shellCommand() {
  if (process.platform === "win32") {
    return { command: process.env.ComSpec || "cmd.exe", args: [] };
  }
  const shell = process.env.SHELL || "/bin/zsh";
  return { command: existsSync(shell) ? shell : "/bin/sh", args: ["-l", "-i"] };
}

/** One shell, its emulator, and whoever is watching it. */
class Shell {
  constructor(id, { cwd, cols, rows }) {
    const { command, args } = shellCommand();
    this.id = id;
    this.cwd = cwd;
    this.attached = 0;
    this.lastSeen = Date.now();
    this._sinks = new Set();
    this._frame = null;
    // TERM matters as much as PATH: a shell told "dumb" prints no colour and
    // no prompt decoration, which would make a colour terminal pointless.
    // COLORTERM is what programs check before emitting 24-bit SGR.
    const env = { ...agentEnv(), TERM: "xterm-256color", COLORTERM: "truecolor" };
    this.pty = new PtySession(`term:${id}`, {
      command,
      args,
      cwd: cwd && existsSync(cwd) ? cwd : os.homedir(),
      env,
      cols: cols || COLS,
      rows: rows || ROWS,
    });
    // The PtySession already feeds its own Screen — reuse it rather than
    // running a second emulator over the same bytes.
    this.screen = this.pty._screen;
    this.pty.onData((chunk) => this._onData(chunk));
    this.exited = this.pty.exited;
  }

  _onData(chunk) {
    this.lastSeen = Date.now();
    // The emulator answers queries the shell makes of its terminal (DA, DSR,
    // cursor position). Nobody else can: those replies are generated BY the
    // emulator, and a shell that asks "what are you?" and hears nothing can
    // stall before it ever prints a prompt. Written straight back to the PTY.
    const reply = this.screen.takeResponse();
    if (reply) this.pty.write(reply);

    for (const sink of this._sinks) {
      if (sink.format === "raw") {
        try {
          sink.send({ raw: chunk });
        } catch {}
      }
    }
    // Cell sinks are served on a frame timer, not per chunk — see FRAME_MS.
    if (this._sinks.size && !this._frame) {
      this._frame = setTimeout(() => {
        this._frame = null;
        this._flush();
      }, FRAME_MS);
    }
  }

  /** Push the rows that changed since the last frame to every cell watcher. */
  _flush() {
    const cellSinks = [...this._sinks].filter((s) => s.format === "cells");
    if (!cellSinks.length) return;
    // ONE read of the dirty rows for all of them — `dirtyOnly` clears the marks,
    // so reading per sink would give each watcher a different slice of the
    // update and leave every screen but the first incomplete.
    const frame = this.screen.cells({ dirtyOnly: true });
    if (!frame.lines.length && !frame.cursor) return;
    for (const sink of cellSinks) {
      try {
        sink.send(frame);
      } catch {}
    }
  }

  /** The whole screen — what a newly-attached client paints before deltas. */
  snapshot() {
    return this.screen.cells();
  }

  attach(sink) {
    this._sinks.add(sink);
    this.attached++;
    this.lastSeen = Date.now();
    return () => {
      this._sinks.delete(sink);
      this.attached--;
      this.lastSeen = Date.now();
    };
  }

  write(data) {
    this.lastSeen = Date.now();
    this.pty.write(data);
  }

  resize(cols, rows) {
    this.pty.resize(cols, rows);
    // Re-paint everyone: a resize reflows the whole grid, and the dirty marks
    // don't necessarily cover rows that only MOVED.
    for (const sink of this._sinks) {
      if (sink.format !== "cells") continue;
      try {
        sink.send(this.snapshot());
      } catch {}
    }
  }

  kill() {
    if (this._frame) clearTimeout(this._frame);
    this._frame = null;
    this._sinks.clear();
    this.pty.kill("SIGKILL");
  }
}

const shells = new Map();

/** Get the thread's shell, starting one if it isn't running.
 *  Idempotent by design: the dock calls it on every open, and re-opening must
 *  return to the same session with its scrollback, not a fresh prompt. */
export function openShell(id, { cwd, cols, rows } = {}) {
  let shell = shells.get(id);
  if (shell && shell.pty.exitCode == null) return shell;
  shell = new Shell(id, { cwd, cols, rows });
  shells.set(id, shell);
  shell.exited.finally(() => {
    if (shells.get(id) === shell) shells.delete(id);
  });
  return shell;
}

export function getShell(id) {
  const shell = shells.get(id);
  return shell && shell.pty.exitCode == null ? shell : null;
}

export function closeShell(id) {
  const shell = shells.get(id);
  if (!shell) return false;
  shell.kill();
  shells.delete(id);
  return true;
}

/** Whether a thread has a live shell — the dock asks so it can reopen where you
 *  left it without starting one on a thread you never opened it on. */
export function hasShell(id) {
  return getShell(id) != null;
}

/**
 * Kill shells nobody has watched for a while.
 *
 * Called on a timer by the server. Only unattached ones: a dock left open in a
 * background tab is still wanted, and its `lastSeen` only moves on output.
 */
export function reapShells(now = Date.now()) {
  let killed = 0;
  for (const [id, shell] of shells) {
    if (shell.attached > 0) continue;
    if (now - shell.lastSeen < REAP_MS) continue;
    shell.kill();
    shells.delete(id);
    killed++;
  }
  return killed;
}

/** Drop every shell — bridge shutdown. */
export function killAllShells() {
  for (const shell of shells.values()) shell.kill();
  shells.clear();
}
