// Let Android reach a Pounce Bridge on the local network.
//
// Every bridge address is plain HTTP: the LAN one from a pairing code
// (http://192.168.x.x:8099) and the Iroh tunnel's own loopback proxy
// (http://127.0.0.1:…). Android blocks ALL cleartext by default from targetSdk
// 28 on, so a release build could not reach either — pairing failed with
// "Couldn't reach that computer" no matter which network the phone was on,
// while iOS worked because it declares NSAllowsLocalNetworking.
//
// This permits cleartext GENERALLY, which deserves an explanation, because the
// obvious tighter version does not work: Android's <domain> rules match a
// hostname or a single IP literal — CIDR ranges are NOT supported — so there is
// no way to write "any RFC-1918 address". A pairing code carries whatever
// address the host happens to have (192.168.1.3 today, 10.0.0.7 on another
// network), so an enumerated allowlist would fail exactly where it matters.
// iOS gets NSAllowsLocalNetworking, which has no Android equivalent.
//
// android/ is gitignored (prebuild generates it), so this has to be a plugin.
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");
const fs = require("node:fs");
const path = require("node:path");

const FILE = "network_security_config.xml";
const XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withLocalNetworkCleartext.js — do not edit by hand. -->
<network-security-config>
  <!-- A bridge is reached over plain HTTP at whatever address its pairing code
       carries: a LAN IP, or 127.0.0.1 for the Iroh tunnel's loopback proxy.
       <domain> cannot express an IP RANGE, so this cannot be narrowed to
       RFC-1918 — see the plugin header. -->
  <base-config cleartextTrafficPermitted="true">
    <trust-anchors>
      <certificates src="system" />
    </trust-anchors>
  </base-config>
</network-security-config>
`;

module.exports = (config) => {
  config = withDangerousMod(config, [
    "android",
    (c) => {
      const dir = path.join(c.modRequest.platformProjectRoot, "app/src/main/res/xml");
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, FILE), XML);
      return c;
    },
  ]);
  return withAndroidManifest(config, (c) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(c.modResults);
    app.$["android:networkSecurityConfig"] = "@xml/network_security_config";
    return c;
  });
};
